/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComunicacaoRouteImport } from './routes/comunicacao'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as AudiovisualRouteImport } from './routes/audiovisual'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacaoRoute = ComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiovisualRoute = AudiovisualRouteImport.update({
  id: '/audiovisual',
  path: '/audiovisual',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/branding': typeof BrandingRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/contato': typeof ContatoRoute
  '/lab': typeof LabRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/branding': typeof BrandingRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/contato': typeof ContatoRoute
  '/lab': typeof LabRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/branding': typeof BrandingRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/contato': typeof ContatoRoute
  '/lab': typeof LabRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiovisual'
    | '/branding'
    | '/comunicacao'
    | '/contato'
    | '/lab'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiovisual'
    | '/branding'
    | '/comunicacao'
    | '/contato'
    | '/lab'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/audiovisual'
    | '/branding'
    | '/comunicacao'
    | '/contato'
    | '/lab'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiovisualRoute: typeof AudiovisualRoute
  BrandingRoute: typeof BrandingRoute
  ComunicacaoRoute: typeof ComunicacaoRoute
  ContatoRoute: typeof ContatoRoute
  LabRoute: typeof LabRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacao': {
      id: '/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof ComunicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiovisual': {
      id: '/audiovisual'
      path: '/audiovisual'
      fullPath: '/audiovisual'
      preLoaderRoute: typeof AudiovisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiovisualRoute: AudiovisualRoute,
  BrandingRoute: BrandingRoute,
  ComunicacaoRoute: ComunicacaoRoute,
  ContatoRoute: ContatoRoute,
  LabRoute: LabRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
