/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EstrategiaRouteImport } from './routes/estrategia'
import { Route as CriacaoRouteImport } from './routes/criacao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as AudiovisualRouteImport } from './routes/audiovisual'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiaRoute = EstrategiaRouteImport.update({
  id: '/estrategia',
  path: '/estrategia',
  getParentRoute: () => rootRouteImport,
} as any)
const CriacaoRoute = CriacaoRouteImport.update({
  id: '/criacao',
  path: '/criacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiovisualRoute = AudiovisualRouteImport.update({
  id: '/audiovisual',
  path: '/audiovisual',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/branding': typeof BrandingRoute
  '/contato': typeof ContatoRoute
  '/criacao': typeof CriacaoRoute
  '/estrategia': typeof EstrategiaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/branding': typeof BrandingRoute
  '/contato': typeof ContatoRoute
  '/criacao': typeof CriacaoRoute
  '/estrategia': typeof EstrategiaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/branding': typeof BrandingRoute
  '/contato': typeof ContatoRoute
  '/criacao': typeof CriacaoRoute
  '/estrategia': typeof EstrategiaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiovisual'
    | '/branding'
    | '/contato'
    | '/criacao'
    | '/estrategia'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiovisual'
    | '/branding'
    | '/contato'
    | '/criacao'
    | '/estrategia'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/audiovisual'
    | '/branding'
    | '/contato'
    | '/criacao'
    | '/estrategia'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiovisualRoute: typeof AudiovisualRoute
  BrandingRoute: typeof BrandingRoute
  ContatoRoute: typeof ContatoRoute
  CriacaoRoute: typeof CriacaoRoute
  EstrategiaRoute: typeof EstrategiaRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategia': {
      id: '/estrategia'
      path: '/estrategia'
      fullPath: '/estrategia'
      preLoaderRoute: typeof EstrategiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criacao': {
      id: '/criacao'
      path: '/criacao'
      fullPath: '/criacao'
      preLoaderRoute: typeof CriacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiovisual': {
      id: '/audiovisual'
      path: '/audiovisual'
      fullPath: '/audiovisual'
      preLoaderRoute: typeof AudiovisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiovisualRoute: AudiovisualRoute,
  BrandingRoute: BrandingRoute,
  ContatoRoute: ContatoRoute,
  CriacaoRoute: CriacaoRoute,
  EstrategiaRoute: EstrategiaRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
